### PR TITLE
Demonstrate how to use the demo server for #67

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by Robinlovelace** [comment]
This outlines an approach. Wouldn't be too much work to do for other functions but wanted to check the approach, which seems to work for all 3 modes. Enabling the user to specify `osrm.server` and `osrm.profile` in function calls is worthwhile IMO. Also happy for this to be merged and for you change/tidy as appropriate @rCarto. This will mean less work my end on https://github.com/ropensci/stplanr/issues/449 and benefit users, not least from a documentation perspective, great to see the results:

**Comment by Robinlovelace** [comment]
``` r
remotes::install_github("robinlovelace/osrm", "demo-server-multimodal")
#> Using github PAT from envvar GITHUB_PAT
#> Skipping install of 'osrm' from a github remote, the SHA1 (2c76882d) has not changed since last install.
#>   Use `force = TRUE` to force installation
library(osrm)
#> Data: (c) OpenStreetMap contributors, ODbL 1.0 - http://www.openstreetmap.org/copyright
#> Routing: OSRM - http://project-osrm.org/
library(sf)
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 7.0.0

u <- "https://routing.openstreetmap.de/routed-foot/"
route5 <- osrmRoute(apotheke.sf[1, ], apotheke.df[16, ], returnclass="sf", 
                    osrm.server = u)
u <- "https://routing.openstreetmap.de/"
options(osrm.server = u)
route6 <- osrmRoute(apotheke.sf[1, ], apotheke.df[16, ], returnclass="sf", 
                   osrm.profile = "bike")
route7 <- osrmRoute(apotheke.sf[1, ], apotheke.df[16, ], returnclass="sf", 
                   osrm.profile = "car")
plot(st_geometry(route5), col = "green")
plot(st_geometry(route6), add = TRUE) # note the cycle route has fewer turns
plot(st_geometry(route7), col = "red", add = TRUE) # car route, indirect = good!
```



<sup>Created on 2020-12-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Robinlovelace** [comment]
Thanks @rCarto ! I suspect some post-merge tidying will be necessary but the idea + basic implementation is there. FYI I've tested this on 100+ routes and, although this new demo server is slow, it seems pretty reliable.

**Comment by rCarto** [comment]
You're welcome @Robinlovelace , that's a useful addition. 
I've updated all functions, added some tests and github actions. 
IMO the package is almost ready for an update on CRAN.

**Pull request merged**
